import { promises as fs } from "node:fs";
import path from "node:path";
import { describe, expect, test } from "vitest";
import type { BetterAuthOptions } from "better-auth";
import { mikroOrmAdapter } from "../src/index.js";
import { createInMemoryOrm, createTempDir } from "./helpers.js";

describe("createSchema", () => {
  test("generates managed MikroORM entity files with transformed names", async () => {
    const orm = await createInMemoryOrm();
    const outputDir = await createTempDir("mikro-orm-better-auth-");
    const options = {
      user: {
        modelName: "members",
        fields: {
          name: "display_name",
          email: "email_address",
        },
      },
    } as BetterAuthOptions;

    const adapter = mikroOrmAdapter(orm.em, {
      generateEntity: {
        outputDir,
      },
    })(options);

    const creation = await adapter.createSchema?.(options, outputDir);
    const entityFile = await fs.readFile(
      path.join(outputDir, "user.entity.ts"),
      "utf8",
    );

    expect(creation?.path).toBe(path.join(outputDir, "user.entity.ts"));
    expect(creation?.code).toContain("@Entity({ tableName: 'members' })");
    expect(entityFile).toContain("@Entity({ tableName: 'members' })");
    expect(entityFile).toContain("fieldName: 'display_name'");
    expect(entityFile).toContain("fieldName: 'email_address'");

    await orm.close(true);
  });

  test("removes stale managed files on regeneration", async () => {
    const orm = await createInMemoryOrm();
    const outputDir = await createTempDir("mikro-orm-better-auth-stale-");
    const options = {} as BetterAuthOptions;
    const adapter = mikroOrmAdapter(orm.em, {
      generateEntity: {
        outputDir,
      },
    })(options);

    await fs.mkdir(outputDir, { recursive: true });
    await fs.writeFile(
      path.join(outputDir, "Stale.ts"),
      "/* This file is auto-generated by mikro-orm-better-auth. Do not edit directly. */\nexport class Stale {}",
      "utf8",
    );

    await adapter.createSchema?.(options, outputDir);

    await expect(
      fs.stat(path.join(outputDir, "Stale.ts")),
    ).rejects.toMatchObject({
      code: "ENOENT",
    });

    await orm.close(true);
  });
});
