import { execFile } from "node:child_process";
import { promises as fs } from "node:fs";
import path from "node:path";
import { promisify } from "node:util";
import { afterEach, describe, expect, test } from "vitest";
import type { BetterAuthOptions } from "better-auth";
import type { BetterAuthDBSchema } from "better-auth/db";
import {
  DEFAULT_OUTPUT_DIR,
  generateEntityFiles,
} from "../src/utils/schema-generator.js";
import { createTempDir } from "./helpers.js";

const originalCwd = process.cwd();
const execFileAsync = promisify(execFile);

afterEach(() => {
  process.chdir(originalCwd);
});

describe("schema generator utilities", () => {
  test("generates entity files for a directory target with custom settings", async () => {
    const workspaceDir = await createTempDir("mikro-orm-better-auth-schema-");
    const outputDir = path.join(workspaceDir, "entities");
    const tables = {
      report: {
        modelName: "reports",
        order: 1,
        fields: {
          title: {
            type: "string",
            defaultValue: "draft",
            unique: true,
            index: true,
            fieldName: "report_title",
          },
          score: {
            type: "number",
          },
          active: {
            type: "boolean",
            defaultValue: false,
          },
          createdAt: {
            type: "date",
            defaultValue: () => new Date(),
          },
          updatedAt: {
            type: "date",
            required: false,
            onUpdate: () => new Date(),
          },
          metadata: {
            type: "json",
            required: false,
          },
          tags: {
            type: "string[]",
            required: false,
          },
          scores: {
            type: "number[]",
            required: false,
          },
        },
      },
    } satisfies BetterAuthDBSchema;

    const result = await generateEntityFiles({
      file: outputDir,
      tables,
      options: {
        advanced: {
          database: {
            generateId: "serial",
          },
        },
      } as BetterAuthOptions,
    });

    const entityFile = path.join(outputDir, "report.entity.ts");
    const entityCode = await fs.readFile(entityFile, "utf8");

    expect(result.path).toBe(entityFile);
    expect(result.overwrite).toBe(true);
    expect(result.code).not.toContain(
      "auto-generated by mikro-orm-better-auth",
    );
    expect(entityCode).not.toContain("auto-generated by mikro-orm-better-auth");
    expect(entityCode).not.toContain("mikro-orm-better-auth-managed");
    expect(entityCode).toContain(
      'import { Entity, PrimaryKey, Property } from "@mikro-orm/core";\n\n@Entity({ tableName: "reports" })',
    );
    expect(entityCode).toContain(
      '@PrimaryKey({ type: "number", autoincrement: true })',
    );
    expect(entityCode).toContain('fieldName: "report_title"');
    expect(entityCode).toContain("nullable: true");
    expect(entityCode).toContain("unique: true");
    expect(entityCode).toContain("index: true");
    expect(entityCode).toContain('default: "draft"');
    expect(entityCode).toContain("default: false");
    expect(entityCode).toContain("onCreate: () => new Date()");
    expect(entityCode).toContain("onUpdate: () => new Date()");
    expect(entityCode).toContain(
      "metadata?: Record<string, unknown> | unknown[];",
    );
    expect(entityCode).toContain("tags?: string[];");
    expect(entityCode).toContain("scores?: number[];");
    expect(entityCode).toContain("createdAt: Date = new Date();");
    expect(entityCode).not.toMatch(/\n{3,}/);

    await expectGeneratedFilesToTypecheck(workspaceDir);
  });

  test("uses the default output directory when no file path is provided", async () => {
    const workspaceDir = await createTempDir(
      "mikro-orm-better-auth-default-schema-",
    );
    process.chdir(workspaceDir);

    const result = await generateEntityFiles({
      tables: {
        user: {
          modelName: "users",
          fields: {
            email: {
              type: "string",
            },
          },
        },
      },
      options: {} as BetterAuthOptions,
    });

    const expectedPath = path.join(
      workspaceDir,
      DEFAULT_OUTPUT_DIR,
      "user.entity.ts",
    );
    const entityFile = path.join(
      workspaceDir,
      DEFAULT_OUTPUT_DIR,
      "user.entity.ts",
    );

    expect(await fs.realpath(result.path)).toBe(
      await fs.realpath(expectedPath),
    );
    await expect(fs.stat(entityFile)).resolves.toBeDefined();
  });

  test("patches managed files while preserving handwritten imports decorators members and comments", async () => {
    const outputDir = await createTempDir("mikro-orm-better-auth-patch-");
    const entityPath = path.join(outputDir, "user.entity.ts");

    await generateEntityFiles({
      file: outputDir,
      tables: {
        user: {
          modelName: "users",
          fields: {
            email: {
              type: "string",
            },
          },
        },
      },
      options: {} as BetterAuthOptions,
    });

    const initialCode = await fs.readFile(entityPath, "utf8");
    const customizedCode = initialCode
      .replace(
        'import { Entity, PrimaryKey, Property } from "@mikro-orm/core";',
        'import { Entity, PrimaryKey, Property } from "@mikro-orm/core";\nimport { Field, ObjectType } from "@nestjs/graphql";\nimport { IsEmail } from "class-validator";',
      )
      .replace(
        '@Entity({ tableName: "users" })',
        '@ObjectType()\n@Entity({ tableName: "users" })',
      )
      .replace(
        '@Property({ type: "string" })\n  email!: string;',
        '/** User email doc */\n  @Field()\n  @IsEmail()\n  @Property({ type: "string" })\n  email!: string;',
      )
      .replace(
        "\n}",
        "\n\n  // Extra user-owned property.\n  @Field({ nullable: true })\n  nickname?: string;\n\n  get displayEmail() {\n    return this.email;\n  }\n}",
      );

    await fs.writeFile(entityPath, customizedCode, "utf8");

    await generateEntityFiles({
      file: outputDir,
      tables: {
        user: {
          modelName: "members",
          fields: {
            email: {
              type: "string",
              fieldName: "email_address",
            },
            name: {
              type: "string",
              required: false,
            },
          },
        },
      },
      options: {} as BetterAuthOptions,
    });

    const patchedCode = await fs.readFile(entityPath, "utf8");

    expect(patchedCode).not.toContain(
      "auto-generated by mikro-orm-better-auth",
    );
    expect(patchedCode).not.toContain("mikro-orm-better-auth-managed");
    expect(patchedCode).toContain(
      'import { Field, ObjectType } from "@nestjs/graphql";',
    );
    expect(patchedCode).toContain('import { IsEmail } from "class-validator";');
    expect(patchedCode).toContain("@ObjectType()");
    expect(patchedCode).toContain("/** User email doc */");
    expect(patchedCode).toContain("@Field()");
    expect(patchedCode).toContain("@IsEmail()");
    expect(patchedCode).toContain('@Entity({ tableName: "members" })');
    expect(patchedCode).toContain(
      '@Property({ fieldName: "email_address", type: "string" })',
    );
    expect(patchedCode).toContain("nickname?: string;");
    expect(patchedCode).toContain("get displayEmail()");
    expect(patchedCode).toContain("name?: string;");
    expect(patchedCode).not.toMatch(/\n{3,}/);
  });

  test("keeps existing unmatched properties while preserving user-owned members", async () => {
    const workspaceDir = await createTempDir("mikro-orm-better-auth-stale-");
    const outputDir = path.join(workspaceDir, "entities");
    const entityPath = path.join(outputDir, "user.entity.ts");

    await generateEntityFiles({
      file: outputDir,
      tables: {
        user: {
          modelName: "users",
          fields: {
            email: {
              type: "string",
            },
            name: {
              type: "string",
            },
          },
        },
      },
      options: {} as BetterAuthOptions,
    });

    const initialCode = await fs.readFile(entityPath, "utf8");
    const customizedCode = initialCode.replace(
      "\n}",
      "\n\n  /** User-owned comment */\n  nickname?: string;\n\n  get displayEmail() {\n    return this.email;\n  }\n}",
    );

    await fs.writeFile(entityPath, customizedCode, "utf8");

    await generateEntityFiles({
      file: outputDir,
      tables: {
        user: {
          modelName: "users",
          fields: {
            email: {
              type: "string",
              fieldName: "email_address",
            },
          },
        },
      },
      options: {} as BetterAuthOptions,
    });

    const patchedCode = await fs.readFile(entityPath, "utf8");

    expect(patchedCode).toContain("name!: string;");
    expect(patchedCode).toContain('fieldName: "email_address"');
    expect(patchedCode).toContain("/** User-owned comment */");
    expect(patchedCode).toContain("nickname?: string;");
    expect(patchedCode).toContain("get displayEmail()");

    await expectGeneratedFilesToTypecheck(workspaceDir);
  });

  test("fails when a managed file no longer contains the expected exported entity class", async () => {
    const outputDir = await createTempDir(
      "mikro-orm-better-auth-invalid-managed-",
    );
    const entityPath = path.join(outputDir, "user.entity.ts");

    await generateEntityFiles({
      file: outputDir,
      tables: {
        user: {
          modelName: "users",
          fields: {
            email: {
              type: "string",
            },
          },
        },
      },
      options: {} as BetterAuthOptions,
    });

    const initialCode = await fs.readFile(entityPath, "utf8");
    await fs.writeFile(
      entityPath,
      initialCode.replace("export class User", "export class Member"),
      "utf8",
    );

    await expect(
      generateEntityFiles({
        file: outputDir,
        tables: {
          user: {
            modelName: "users",
            fields: {
              email: {
                type: "string",
              },
            },
          },
        },
        options: {} as BetterAuthOptions,
      }),
    ).rejects.toThrow("could not be patched safely");
  });

  test("fails when an existing file does not contain the expected exported entity class", async () => {
    const outputDir = await createTempDir("mikro-orm-better-auth-unmanaged-");
    const tableSchema = {
      user: {
        modelName: "users",
        fields: {
          email: {
            type: "string",
          },
        },
      },
    } satisfies BetterAuthDBSchema;
    const target = path.join(outputDir, "user.entity.ts");

    await fs.writeFile(target, "export class Member {}\n", "utf8");

    await expect(
      generateEntityFiles({
        file: outputDir,
        tables: tableSchema,
        options: {} as BetterAuthOptions,
      }),
    ).rejects.toThrow(`File at ${target} could not be patched safely`);
  });

  test("fails with a clear error when Prettier config cannot be resolved", async () => {
    const workspaceDir = await createTempDir(
      "mikro-orm-better-auth-invalid-prettier-",
    );
    const outputDir = path.join(workspaceDir, "entities");

    await fs.writeFile(
      path.join(workspaceDir, ".prettierrc.json"),
      "{ invalid json }\n",
      "utf8",
    );

    await expect(
      generateEntityFiles({
        file: outputDir,
        tables: {
          user: {
            modelName: "users",
            fields: {
              email: {
                type: "string",
              },
            },
          },
        },
        options: {} as BetterAuthOptions,
      }),
    ).rejects.toThrow("Failed to format generated file");
  });
});

async function expectGeneratedFilesToTypecheck(workspaceDir: string) {
  const tsconfigPath = path.join(workspaceDir, "tsconfig.json");

  await fs.writeFile(
    tsconfigPath,
    JSON.stringify(
      {
        compilerOptions: {
          target: "ES2022",
          module: "NodeNext",
          moduleResolution: "NodeNext",
          strict: true,
          experimentalDecorators: true,
          emitDecoratorMetadata: true,
          noEmit: true,
          skipLibCheck: true,
          types: ["node"],
        },
        include: ["entities/**/*.ts"],
      },
      null,
      2,
    ),
    "utf8",
  );

  await execFileAsync(
    process.execPath,
    [
      path.join(originalCwd, "node_modules/typescript/bin/tsc"),
      "--project",
      tsconfigPath,
    ],
    {
      cwd: workspaceDir,
    },
  );
}
