import { promises as fs } from "node:fs";
import path from "node:path";
import { Project, QuoteKind, ScriptTarget, SourceFile, ts } from "ts-morph";
import type { BetterAuthOptions } from "better-auth";
import type { DBAdapterSchemaCreation } from "better-auth/adapters";
import type {
  BetterAuthDBSchema,
  DBFieldAttribute,
  DBFieldType,
} from "better-auth/db";
import type { MikroOrmGenerateEntityConfig } from "../types.js";
import { escapeString, toKebabCase, toPascalCase } from "./string.js";

export const MANAGED_FILE_HEADER =
  "/* This file is auto-generated by mikro-orm-better-auth. Do not edit directly. */";
export const DEFAULT_OUTPUT_DIR = "src/auth/entities";

export async function generateEntityFiles({
  file,
  tables,
  options,
  generateEntityConfig,
}: {
  file?: string;
  tables: BetterAuthDBSchema;
  options: BetterAuthOptions;
  generateEntityConfig?: MikroOrmGenerateEntityConfig;
}): Promise<DBAdapterSchemaCreation> {
  const generation = resolveGenerationPaths(file, generateEntityConfig);
  const managedComment =
    generateEntityConfig?.managedComment ?? MANAGED_FILE_HEADER;

  await fs.mkdir(generation.outputDir, { recursive: true });

  const project = new Project({
    compilerOptions: {
      target: ScriptTarget.ES2022,
      experimentalDecorators: true,
      emitDecoratorMetadata: true,
    },
    manipulationSettings: {
      quoteKind: QuoteKind.Single,
    },
    useInMemoryFileSystem: false,
  });

  const expectedPaths = new Set<string>();
  const generatedPaths: string[] = [];
  const sortedTables = Object.entries(tables).sort(([, left], [, right]) => {
    return (
      (left.order ?? Number.MAX_SAFE_INTEGER) -
      (right.order ?? Number.MAX_SAFE_INTEGER)
    );
  });

  for (const [modelKey, table] of sortedTables) {
    const entityPath = path.join(
      generation.outputDir,
      toEntityFileName(modelKey),
    );

    expectedPaths.add(entityPath);
    generatedPaths.push(entityPath);
    await ensureManagedFileCanBeWritten(entityPath, managedComment);

    const sourceFile = project.createSourceFile(entityPath, "", {
      overwrite: true,
    });

    buildEntitySourceFile({
      sourceFile,
      managedComment,
      modelKey,
      table,
      options,
    });
  }

  await deleteStaleManagedFiles(
    generation.outputDir,
    expectedPaths,
    managedComment,
  );
  await project.save();

  const primaryPath = generatedPaths[0];

  if (!primaryPath) {
    throw new Error("No Better Auth entities were generated.");
  }

  const code = await fs.readFile(primaryPath, "utf8");

  return {
    path: primaryPath,
    code,
    overwrite: true,
  };
}

function resolveGenerationPaths(
  file: string | undefined,
  generateEntityConfig: MikroOrmGenerateEntityConfig | undefined,
) {
  if (!file) {
    const outputDir = path.resolve(
      generateEntityConfig?.outputDir ?? DEFAULT_OUTPUT_DIR,
    );
    return {
      outputDir,
    };
  }

  const resolved = path.resolve(file);

  if (path.extname(resolved)) {
    return {
      outputDir: path.dirname(resolved),
    };
  }

  return {
    outputDir: resolved,
  };
}

async function ensureManagedFileCanBeWritten(
  filePath: string,
  managedComment: string,
) {
  try {
    const existing = await fs.readFile(filePath, "utf8");

    if (!existing.startsWith(managedComment)) {
      throw new Error(
        `Refusing to overwrite unmanaged file at ${filePath}. Move it or point generateEntity at a dedicated output path.`,
      );
    }
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code === "ENOENT") {
      return;
    }

    throw error;
  }
}

async function deleteStaleManagedFiles(
  outputDir: string,
  expectedPaths: Set<string>,
  managedComment: string,
) {
  const entries = await fs.readdir(outputDir, { withFileTypes: true });

  await Promise.all(
    entries.map(async (entry) => {
      if (!entry.isFile() || !entry.name.endsWith(".ts")) {
        return;
      }

      const fullPath = path.join(outputDir, entry.name);

      if (expectedPaths.has(fullPath)) {
        return;
      }

      const content = await fs.readFile(fullPath, "utf8");
      if (content.startsWith(managedComment)) {
        await fs.unlink(fullPath);
      }
    }),
  );
}

function buildEntitySourceFile({
  sourceFile,
  managedComment,
  modelKey,
  table,
  options,
}: {
  sourceFile: SourceFile;
  managedComment: string;
  modelKey: string;
  table: BetterAuthDBSchema[string];
  options: BetterAuthOptions;
}) {
  const className = toPascalCase(modelKey);
  const generateIdMode = options.advanced?.database?.generateId;

  sourceFile.addStatements(managedComment);
  sourceFile.addStatements("");
  sourceFile.addImportDeclaration({
    moduleSpecifier: "@mikro-orm/core",
    namedImports: ["Entity", "PrimaryKey", "Property"],
  });
  sourceFile.addStatements("");

  const entityClass = sourceFile.addClass({
    name: className,
    isExported: true,
    decorators: [
      {
        name: "Entity",
        arguments: [`{ tableName: '${table.modelName}' }`],
      },
    ],
  });

  entityClass.addProperty({
    name: "id",
    type: generateIdMode === "serial" ? "number" : "string",
    hasExclamationToken: true,
    decorators: [
      {
        name: "PrimaryKey",
        arguments: [
          serializeDecoratorOptions({
            type: generateIdMode === "serial" ? "number" : "string",
            autoincrement: generateIdMode === "serial" ? true : undefined,
          }),
        ],
      },
    ],
  });

  for (const [fieldName, field] of Object.entries(table.fields)) {
    const initializer = buildInitializer(field);

    entityClass.addProperty({
      name: fieldName,
      type: mapFieldTypeToTypeScript(field.type),
      hasExclamationToken:
        field.required !== false && initializer === undefined,
      hasQuestionToken: field.required === false,
      initializer,
      decorators: [
        {
          name: "Property",
          arguments: [
            serializeDecoratorOptions(toPropertyOptions(field, fieldName)),
          ],
        },
      ],
    });
  }

  sourceFile.formatText({
    indentSize: 2,
    convertTabsToSpaces: true,
    semicolons: ts.SemicolonPreference.Insert,
  });
}

function toPropertyOptions(field: DBFieldAttribute, fieldName: string) {
  return {
    fieldName:
      field.fieldName && field.fieldName !== fieldName
        ? field.fieldName
        : undefined,
    type: mapFieldTypeToMikroOrm(field.type),
    nullable: field.required === false ? true : undefined,
    unique: field.unique ? true : undefined,
    index: field.index ? true : undefined,
    default: buildDefaultOption(field),
    onCreate: buildOnCreateOption(field),
    onUpdate: buildOnUpdateOption(field),
  };
}

function buildDefaultOption(field: DBFieldAttribute) {
  if (typeof field.defaultValue === "string") {
    return field.defaultValue;
  }

  if (
    typeof field.defaultValue === "number" ||
    typeof field.defaultValue === "boolean"
  ) {
    return field.defaultValue;
  }

  return undefined;
}

function buildInitializer(field: DBFieldAttribute) {
  if (typeof field.defaultValue === "string") {
    return `'${escapeString(field.defaultValue)}'`;
  }

  if (
    typeof field.defaultValue === "number" ||
    typeof field.defaultValue === "boolean"
  ) {
    return String(field.defaultValue);
  }

  if (field.type === "date" && field.defaultValue !== undefined) {
    return "new Date()";
  }

  return undefined;
}

function buildOnCreateOption(field: DBFieldAttribute) {
  if (field.type !== "date" || field.defaultValue === undefined) {
    return undefined;
  }

  return "() => new Date()";
}

function buildOnUpdateOption(field: DBFieldAttribute) {
  if (field.type !== "date" || !field.onUpdate) {
    return undefined;
  }

  return "() => new Date()";
}

function serializeDecoratorOptions(options: Record<string, unknown>) {
  const parts = Object.entries(options)
    .filter(([, value]) => value !== undefined)
    .map(([key, value]) => `${key}: ${serializeDecoratorValue(value)}`);

  return parts.length > 0 ? `{ ${parts.join(", ")} }` : "{}";
}

function serializeDecoratorValue(value: unknown): string {
  if (typeof value === "string") {
    if (value.startsWith("() => ")) {
      return value;
    }

    if (value === "Date") {
      return "Date";
    }

    return `'${escapeString(value)}'`;
  }

  if (typeof value === "number" || typeof value === "boolean") {
    return String(value);
  }

  if (value === null) {
    return "null";
  }

  return JSON.stringify(value);
}

function mapFieldTypeToTypeScript(type: DBFieldType) {
  if (Array.isArray(type)) {
    return "string";
  }

  switch (type) {
    case "number":
      return "number";
    case "boolean":
      return "boolean";
    case "date":
      return "Date";
    case "json":
      return "Record<string, unknown> | unknown[]";
    case "string[]":
      return "string[]";
    case "number[]":
      return "number[]";
    case "string":
    default:
      return "string";
  }
}

function mapFieldTypeToMikroOrm(type: DBFieldType) {
  if (Array.isArray(type)) {
    return "string";
  }

  switch (type) {
    case "date":
      return "Date";
    case "json":
    case "string[]":
    case "number[]":
      return "json";
    default:
      return type;
  }
}

function toEntityFileName(modelKey: string) {
  return `${toKebabCase(modelKey)}.entity.ts`;
}
